# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.7.9999
#hackport: flags: -bytestring-builder,-developer

CABAL_FEATURES="lib profile haddock hoogle hscolour"
# break circular dependencies:
# https://github.com/gentoo-haskell/gentoo-haskell/issues/810
CABAL_FEATURES+=" nocabaldep"
inherit haskell-cabal

RESTRICT="test" # Circular dependencies

DESCRIPTION="An efficient packed Unicode text type"
HOMEPAGE="https://github.com/haskell/text"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD-2"
SLOT="0/${PV}"
# keep in sync with ghc-9.2.1
KEYWORDS=""

RDEPEND=">=dev-lang/ghc-8.4.3:=
"
DEPEND="${RDEPEND}
"
#	test? ( >=dev-haskell/quickcheck-2.14.1 <dev-haskell/quickcheck-2.15
#		>=dev-haskell/quickcheck-unicode-1.0.1.0
#		dev-haskell/random
#		dev-haskell/tasty
#		dev-haskell/tasty-hunit
#		dev-haskell/tasty-inspection-testing
#		dev-haskell/tasty-quickcheck )

CABAL_CORE_LIB_GHC_PV="PM:9.2.1 PM:9999"

src_configure() {
	haskell-cabal_src_configure \
		--flag=-bytestring-builder \
		--flag=-developer
}
